#!/usr/bin/env python3
"""Convert NIST ACVP ML-KEM test vectors (prompt + expectedResults JSON
pairs) into a self-contained Zig source file consumed by tests/kats.zig.

We filter to a single parameter set (typically ML-KEM-768), pair each
prompt by tcId with its expected output, and emit hex byte arrays as
Zig array literals grouped into per-operation slices."""

import argparse
import json
import sys
import textwrap


def hex_to_zig_bytes(hex_str: str) -> str:
    """Format a hex string as a Zig byte literal: 0xff, 0x00, ..."""
    raw = bytes.fromhex(hex_str)
    chunks = []
    for i in range(0, len(raw), 16):
        line = ", ".join(f"0x{b:02x}" for b in raw[i : i + 16])
        chunks.append("        " + line + ",")
    return "\n".join(chunks)


def emit_array(name: str, hex_str: str, length: int, out) -> None:
    raw = bytes.fromhex(hex_str)
    if len(raw) != length:
        raise ValueError(f"{name}: expected {length} bytes, got {len(raw)}")
    out.write(f"        .{name} = [_]u8{{\n")
    out.write(hex_to_zig_bytes(hex_str))
    out.write("\n        },\n")


def index_by_tcid(test_groups, parameter_set=None, function=None):
    """Return {tcId: test_dict} for tests in groups matching the filters.

    The expectedResults.json files don't replicate parameterSet/function
    on their groups — only prompt.json does. So callers filter prompts
    by parameter_set/function, then look up expectedResults purely by
    tcId (which is globally unique within a file)."""
    out = {}
    for g in test_groups:
        if parameter_set is not None and g.get("parameterSet") != parameter_set:
            continue
        if function is not None and g.get("function") != function:
            continue
        for t in g.get("tests", []):
            out[t["tcId"]] = t
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--keygen-prompt", required=True)
    ap.add_argument("--keygen-expected", required=True)
    ap.add_argument("--encap-prompt", required=True)
    ap.add_argument("--encap-expected", required=True)
    ap.add_argument("--parameter-set", default="ML-KEM-768")
    ap.add_argument("--output", required=True)
    args = ap.parse_args()

    # Per FIPS-203 ML-KEM-768.
    EK_LEN = 1184
    DK_LEN = 2400
    CT_LEN = 1088
    K_LEN = 32
    SEED_LEN = 32

    keygen_prompt = json.load(open(args.keygen_prompt))
    keygen_expected = json.load(open(args.keygen_expected))
    encap_prompt = json.load(open(args.encap_prompt))
    encap_expected = json.load(open(args.encap_expected))

    keygen_in = index_by_tcid(keygen_prompt["testGroups"], args.parameter_set)
    keygen_out = index_by_tcid(keygen_expected["testGroups"])

    encap_in = index_by_tcid(encap_prompt["testGroups"], args.parameter_set, "encapsulation")
    encap_out = index_by_tcid(encap_expected["testGroups"])

    decap_in = index_by_tcid(encap_prompt["testGroups"], args.parameter_set, "decapsulation")
    decap_out = index_by_tcid(encap_expected["testGroups"])

    with open(args.output, "w") as out:
        out.write(textwrap.dedent(f"""\
            //! GENERATED by scripts/build-acvp.sh — do not hand-edit.
            //!
            //! NIST ACVP test vectors for {args.parameter_set} (FIPS-203),
            //! sourced from https://github.com/usnistgov/ACVP-Server.
            //! These exercise the underlying KEM primitive directly,
            //! independent of any PQNoise protocol layering.
            //!
            //! Re-run scripts/build-acvp.sh to regenerate.

            pub const generated: bool = true;

            pub const KeyGenTest = struct {{
                tc_id: u32,
                d: [{SEED_LEN}]u8,
                z: [{SEED_LEN}]u8,
                ek: [{EK_LEN}]u8,
                dk: [{DK_LEN}]u8,
            }};

            pub const EncapTest = struct {{
                tc_id: u32,
                ek: [{EK_LEN}]u8,
                m: [{SEED_LEN}]u8,
                ct: [{CT_LEN}]u8,
                k: [{K_LEN}]u8,
            }};

            pub const DecapTest = struct {{
                tc_id: u32,
                dk: [{DK_LEN}]u8,
                c: [{CT_LEN}]u8,
                k: [{K_LEN}]u8,
            }};

            pub const keygen: []const KeyGenTest = &.{{
        """))

        for tc_id in sorted(keygen_in):
            inp = keygen_in[tc_id]
            outp = keygen_out[tc_id]
            out.write(f"    .{{\n        .tc_id = {tc_id},\n")
            emit_array("d", inp["d"], SEED_LEN, out)
            emit_array("z", inp["z"], SEED_LEN, out)
            emit_array("ek", outp["ek"], EK_LEN, out)
            emit_array("dk", outp["dk"], DK_LEN, out)
            out.write("    },\n")
        out.write("};\n\n")

        out.write("pub const encap: []const EncapTest = &.{\n")
        for tc_id in sorted(encap_in):
            inp = encap_in[tc_id]
            outp = encap_out[tc_id]
            out.write(f"    .{{\n        .tc_id = {tc_id},\n")
            emit_array("ek", inp["ek"], EK_LEN, out)
            emit_array("m", inp["m"], SEED_LEN, out)
            emit_array("ct", outp["c"], CT_LEN, out)
            emit_array("k", outp["k"], K_LEN, out)
            out.write("    },\n")
        out.write("};\n\n")

        out.write("pub const decap: []const DecapTest = &.{\n")
        for tc_id in sorted(decap_in):
            inp = decap_in[tc_id]
            outp = decap_out[tc_id]
            out.write(f"    .{{\n        .tc_id = {tc_id},\n")
            emit_array("dk", inp["dk"], DK_LEN, out)
            emit_array("c", inp["c"], CT_LEN, out)
            emit_array("k", outp["k"], K_LEN, out)
            out.write("    },\n")
        out.write("};\n")

    print(
        f"Wrote {args.output}: "
        f"{len(keygen_in)} keygen, {len(encap_in)} encap, {len(decap_in)} decap "
        f"vectors for {args.parameter_set}",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
