//! Fuzz target: Connection.recv against adversarial bytes.
//!
//! Builds a real responder Connection per iteration and feeds Smith-
//! generated bytes into recv(). Contract under test:
//!
//!   * No panic, no UB, no slice OOB regardless of input.
//!   * Every error is a member of `pqnoize.Error` (typed).
//!   * Allocator shows zero leaks at end of every iteration.
//!
//! Static keypairs are built once per process (cheap-but-not-free) and
//! reused; only the Connection objects are reconstructed per iteration.
//!
//! Run with:
//!     zig build fuzz-connection         (continuous, --fuzz mode)
//!     zig build fuzz-smoke              (one quick pass, no --fuzz)

const std = @import("std");
const pqnoize = @import("pqnoize");

const Setup = struct {
    initiator_static: pqnoize.kem.Kem.KeyPair,
    responder_static: pqnoize.kem.Kem.KeyPair,
};

fn buildSetup() !Setup {
    var stream = pqnoize.testing.SeedStream.init("fuzz-conn-static");
    return .{
        .initiator_static = try pqnoize.testing.keypair(&stream),
        .responder_static = try pqnoize.testing.keypair(&stream),
    };
}

fn rngFromSeedStream(s: *pqnoize.testing.SeedStream) pqnoize.Rng {
    return .{
        .ctx = s,
        .fillFn = struct {
            fn fill(ctx: *anyopaque, out: []u8) void {
                const stream: *pqnoize.testing.SeedStream = @ptrCast(@alignCast(ctx));
                stream.bytes(out);
            }
        }.fill,
    };
}

test "fuzz: Connection.recv survives arbitrary bytes from init through error" {
    const setup = try buildSetup();
    try std.testing.fuzz(setup, fuzzRecvFromInit, .{});
}

/// Fuzzes recv from a freshly-initialized responder Connection. The
/// adversary can replay handshake bytes, send transport bytes early,
/// fragment in any way — every input must terminate in a typed error
/// or successful processing, never a panic.
fn fuzzRecvFromInit(setup: Setup, smith: *std.testing.Smith) !void {
    const gpa = std.testing.allocator;

    var rng_stream = pqnoize.testing.SeedStream.init("fuzz-conn-r-rng");
    var responder = pqnoize.Connection.initResponder(gpa, .{
        .pattern = &pqnoize.pattern.pqKK,
        .role = .responder,
        .rng = rngFromSeedStream(&rng_stream),
        .s = setup.responder_static,
        .rs = setup.initiator_static.public_key,
    });
    defer responder.deinit();

    while (!smith.eos()) {
        const len = smith.valueRangeAtMost(u32, 1, 4096);
        const buf = try gpa.alloc(u8, len);
        defer gpa.free(buf);
        smith.bytes(buf);

        // Once recv errors, the connection is unusable; further fuzzing
        // would just re-hit the same path. Bail out to give Smith a
        // fresh iteration with a different prefix.
        responder.recv(buf) catch break;

        // Drain any decrypted messages so the inbox doesn't grow without
        // bound across iterations.
        while (responder.nextMessage()) |msg| responder.freeMessage(msg);
    }
}

test "fuzz: Connection.recv post-handshake survives arbitrary bytes" {
    const setup = try buildSetup();
    try std.testing.fuzz(setup, fuzzRecvPostHandshake, .{});
}

/// Fuzzes recv after a successful handshake. This is the more
/// interesting target — exercises the transport AEAD/framing paths
/// with adversarial bytes that the handshake parsers can't reach.
fn fuzzRecvPostHandshake(setup: Setup, smith: *std.testing.Smith) !void {
    const gpa = std.testing.allocator;

    var i_rng = pqnoize.testing.SeedStream.init("fuzz-conn-i");
    var r_rng = pqnoize.testing.SeedStream.init("fuzz-conn-r");

    var initiator = try pqnoize.Connection.initInitiator(gpa, .{
        .pattern = &pqnoize.pattern.pqKK,
        .role = .initiator,
        .rng = rngFromSeedStream(&i_rng),
        .s = setup.initiator_static,
        .rs = setup.responder_static.public_key,
    });
    defer initiator.deinit();

    var responder = pqnoize.Connection.initResponder(gpa, .{
        .pattern = &pqnoize.pattern.pqKK,
        .role = .responder,
        .rng = rngFromSeedStream(&r_rng),
        .s = setup.responder_static,
        .rs = setup.initiator_static.public_key,
    });
    defer responder.deinit();

    // Shuttle handshake bytes manually so we don't fuzz the handshake
    // itself (different test).
    {
        const out = initiator.outgoing();
        const buf = try gpa.alloc(u8, out.len);
        defer gpa.free(buf);
        @memcpy(buf, out);
        initiator.consumeOutgoing(out.len);
        try responder.recv(buf);
    }
    {
        const out = responder.outgoing();
        const buf = try gpa.alloc(u8, out.len);
        defer gpa.free(buf);
        @memcpy(buf, out);
        responder.consumeOutgoing(out.len);
        try initiator.recv(buf);
    }
    if (!responder.isEstablished() or !initiator.isEstablished()) {
        return error.HandshakeFailed;
    }

    while (!smith.eos()) {
        const len = smith.valueRangeAtMost(u32, 1, 4096);
        const buf = try gpa.alloc(u8, len);
        defer gpa.free(buf);
        smith.bytes(buf);

        responder.recv(buf) catch break;
        while (responder.nextMessage()) |msg| responder.freeMessage(msg);
    }
}
